### ISSUE TITLE
Roadmap for v6.0.0

### ISSUE THREAD

**Issue by PeterOrneholm** [ActiveLogin/ActiveLogin.Authentication#357]
This issue is supposed to keep track of the roadmap and todos for v6.0.0.

Todo (things too small to be separate issues)

* [x] Remove all references to manually entered PersonalIdentityNumbers
* [x] Go through and make sure to make as much as possible internal again
* [x] Rename NuGet-packages that don't depend on core
  * [x] Rename ActiveLogin.Authentication.BankId.AspNetCore.Azure to ActiveLogin.Authentication.BankId.AspNetCore.AzureKeyVault
* [x] Remove passing values to script through the form
* [x] Implement BankidUiSignController
* [x] Implement BankIdSignBuilder
* [x] Don't use BankIdHandler for resources
* [x] Go through events and see if they are relevant for auth and sign
* [x] Try to get rid of IOptions for events
* [x] Override context with ProductName = "ActiveLogin-BankId-AspNetCore" when used for that package
* [x] Check if naming of classes are relevant for both auth and sign
* [x] Handle/describe what classes needs to be implemented if the flow is used form core
  * IBankIdEndUserIpResolver
  * IBankIdUserMessageLocalizer
  * IBankIdSupportedDeviceDetector
  * IBankIdInvalidStateHandler
* [x] Document the arhitechturee / flow, try using mermaid flowchart
* [x] Move the localized resources to core
* [x] Fix the staus texts - they are wrong for (at least) other device with QR-code
